# Generated by Django 6.0 on 2026-01-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_alter_fooditems_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foodimages'),
        ),
    ]
