# Generated by Django 6.0 on 2026-01-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_fooditems_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditems',
            old_name='image',
            new_name='menu_image',
        ),
    ]
