# Generated by Django 6.0 on 2026-01-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_image_fooditems_menu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditems',
            old_name='menu_image',
            new_name='image',
        ),
    ]
