# Generated by Django 6.0 on 2026-01-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_menu_image_fooditems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(default='2026-01-29', upload_to='foodimages'),
            preserve_default=False,
        ),
    ]
