# Generated by Django 6.0 on 2026-01-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_fooditems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foodimages'),
        ),
    ]
