# Generated by Django 6.0 on 2026-02-03 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_fooditems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='menu.category'),
        ),
    ]
